name: 'test create issue'
description: 'test create issue'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
runs:
  using: 'node12'
  main: 'dist/index.js'
